qrofind_web/main/urls.py
from django.conf.urls import include, url
from qrofind_web.main import views
urlpatterns = [
    url(r'^$', views.inicio_zonas, name='inicio_zonas'),
    url(r'^zona/(?P<slug_zona>.+)$', views.index, name='index'),
    url(r'^buscar$', views.buscar, name='buscar'),
    url(r'^promociones/generales', views.promociones_generales, name='promociones_generales'),
    url(r'^detalle/articulo/(?P<slug_articulo>.+)$', views.detalle_articulo, name='detalle_articulo'),
]

qrofind_web/negocios/urls.py
from django.conf.urls import include, url
from qrofind_web.negocios import views
urlpatterns = [
    url(r'^categoria/(?P<slug_categoria>.+)/$', views.negocios_categorias, name='negocios_categorias'),
    url(r'^detalle/negocio/(?P<slug_negocio>.+)/$', views.detalle_negocio, name='detalle_negocio'),
    url(r'^registro/clic/$', views.registro_clic_negocio, name='registro_clic_negocio'),
    url(r'^promociones/$', views.promociones, name='promociones'),
    url(r'^anunciate/$', views.anunciate, name='anunciate'),
    url(r'^inicio/anunciate/$', views.anunciate_inicio, name='anunciate_inicio'),
]

qrofind_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Administrador Zona Real'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('qrofind_web.main.urls', namespace="main")),
    url(r'^', include('qrofind_web.negocios.urls', namespace="negocios")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qrofind_web/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from easy_thumbnails.signals import saved_file
from easy_thumbnails.signal_handlers import generate_aliases_global
import binascii
import os
from imagekit.models import ProcessedImageField
from imagekit.processors import Transpose
from qrofind_web.utils import PathAndRename
from django.template.defaultfilters import slugify

saved_file.connect(generate_aliases_global)

path_and_rename_usuarios = PathAndRename("usuarios")
path_and_rename_banners = PathAndRename("banners")
path_and_rename_articulos = PathAndRename("articulos")
path_and_rename_fotos_articulos = PathAndRename("fotos_articulos")
path_and_rename_banner_zona = PathAndRename("banner_zona")

SECCIONES_BANNER = (
    (0, 'Promociones'),
    (1, 'Home Nacional'),
    (2, 'Home Lateral'),
    (3, 'Home Cintillo'),
    (4, 'Home Pie'),
    (5, 'Inicio Zonas Principal'),
    (6, 'Inicio Zonas Lateral'),
    (7, 'Inicio Zonas Banner Pie'),
    (8, 'Home Cintillo 1'),
)


class Usuario(AbstractUser):
    objects = UserManager()
    zona = models.OneToOneField('main.Zona', related_name='usuario', null=True)
    class Meta(AbstractUser.Meta):
        verbose_name = "User"
        verbose_name_plural = "Users"


class Token(models.Model):
    key = models.CharField(max_length=40, primary_key=True)
    user = models.OneToOneField(Usuario, related_name='auth_token')
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super(Token, self).save(*args, **kwargs)

    @staticmethod
    def generate_key():
        return binascii.hexlify(os.urandom(20)).decode()

    def __str__(self):
        return self.key


class Articulo(models.Model):
    titulo = models.CharField(max_length=30)
    imagen = ProcessedImageField(max_length=255, upload_to=path_and_rename_articulos,
                                 processors=[Transpose()])
    descripcion_corta = models.TextField()
    descripcion_larga = models.TextField()
    zona = models.ForeignKey('main.Zona', related_name='articulos')
    slug = models.SlugField(max_length=60, editable=False, unique=True)
    fecha = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo

    def save(self, *args, **kwargs):
        self.slug = slugify(self.titulo)
        return super(Articulo, self).save(*args, **kwargs)



class FotoArticulo(models.Model):
    texto = models.CharField(max_length=100, blank=True, null=True)
    imagen = ProcessedImageField(max_length=255, null=True,
                                 upload_to=path_and_rename_fotos_articulos,
                                 processors=[Transpose()])
    articulo = models.ForeignKey('Articulo', related_name="imagenes")
    orden = models.IntegerField(default=0)

    def __str__(self):
        return self.texto


class Zona(models.Model):
    nombre = models.CharField(max_length=30)
    slug = models.SlugField(max_length=60, editable=False, unique=True)
    imagen = ProcessedImageField(max_length=255, null=True,
                                 upload_to=path_and_rename_banner_zona,
                                 processors=[Transpose()])
    facebook = models.CharField(max_length=50, null=True, blank=True)
    instagram = models.CharField(max_length=50, null=True, blank=True)
    orden = models.IntegerField(default=0)

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        return super(Zona, self).save(*args, **kwargs)


class Banner(models.Model):
    nombre = models.CharField(max_length=50)
    zona = models.ForeignKey('main.Zona', related_name='banners')
    seccion = models.IntegerField(default=0, choices=SECCIONES_BANNER)
    link = models.URLField(max_length=200)
    orden = models.IntegerField(default=0)
    pagina_externa = models.BooleanField(default=False)
    imagen = ProcessedImageField(max_length=255, blank=True, null=True,
                                 upload_to=path_and_rename_banners,
                                 processors=[Transpose()])

    def __str__(self):
        return "{}-{}".format(self.zona, self.nombre)

qrofind_web/main/forms.py
from django import formsfrom qrofind_web.negocios.models import *class BoletinForm(forms.Form):    email = forms.EmailField()    nombre = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))    zona = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Zona'}))

qrofind_web/main/views.py
from django.db.models import Q
from django.shortcuts import render
from qrofind_web.main.forms import *
from qrofind_web.negocios.utils import *


# Create your views here.

def inicio_zonas(request):
    zonas = Zona.objects.all().exclude(slug='default').order_by('orden')
    # zonas_restantes = Zona.objects.all().exclude(slug='default')[6:]
    articulos = Articulo.objects.all().order_by('-id')
    banner_principal = Banner.objects.filter(seccion=5)
    banners_laterales = Banner.objects.filter(seccion=6)
    banner_pie = Banner.objects.filter(seccion=7).order_by('orden')[:1]

    if banner_pie.count() > 0:
        banner_pie = banner_pie[0]
    context = {
        'zonas': zonas,
        # 'zonas_restantes': zonas_restantes,
        'articulos': articulos,
        'banner_laterales': banners_laterales,
        'banners_principales': banner_principal,
        'banner_pie': banner_pie
    }
    return render(request, 'inicio_zonas.html', context)


def promociones_generales(request):
    promociones = Promocion.objects.all()
    zonas = Zona.objects.all().exclude(slug='default').order_by('orden')[:5]
    zonas_restantes = Zona.objects.all().order_by('orden').exclude(slug='default')[6:]
    banner_pie = Banner.objects.filter(seccion=7).order_by('orden')[:1]
    if banner_pie.count() > 0:
        banner_pie = banner_pie[0]

    context = {
        'zonas': zonas,
        'zonas_restantes': zonas_restantes,
        'promociones': promociones,
        'banner_pie': banner_pie
    }
    return render(request, 'promociones_generales.html', context)


def index(request, slug_zona):
    banners_cintillo_nacional = None
    zona = Zona.objects.get(slug=slug_zona)
    # categorias = Categoria.objects.filter(zona=zona).all()

    negocios_premium = Negocio.objects.filter(zona=zona, es_premium=True).order_by('-id')[:4]
    subcategorias_inicio = Subcategoria.objects.filter(categoria__zona=zona, inicio=True).order_by('orden')[:2]
    negocios_primera_subcategoria = subcategorias_inicio[0].negocios.filter(promocionado=True)[:7]
    negocios_segunda_subcategoria = subcategorias_inicio[1].negocios.filter(promocionado=True)[:7]
    request.session['slug_zona_activa'] = slug_zona

    context = {
        'zona': zona,
        # 'categorias': categorias,
        'primera_subcategorias_inicio': subcategorias_inicio[0],
        'segunda_subcategorias_inicio': subcategorias_inicio[1],
        'negocios_primera_subcategoria': negocios_primera_subcategoria,
        'negocios_segunda_subcategoria': negocios_segunda_subcategoria,
        'negocios_premium': negocios_premium
    }
    return render(request, 'index.html', context)


def detalle_articulo(request, slug_articulo):
    articulo = Articulo.objects.get(slug=slug_articulo)
    zonas = Zona.objects.all().order_by('orden').exclude(slug='default')[:5]
    zonas_restantes = Zona.objects.all().order_by('orden').exclude(slug='default')[6:]
    banner_principal = Banner.objects.filter(seccion=5)
    banners_laterales = Banner.objects.filter(seccion=6)
    banner_pie = Banner.objects.filter(seccion=7).order_by('orden')[:1]
    if banner_pie.count() > 0:
        banner_pie = banner_pie[0]
    context = {
        'zonas': zonas,
        'zonas_restantes': zonas_restantes,
        'articulo': articulo,
        'banner_laterales': banners_laterales,
        'banners_principales': banner_principal,
        'banner_pie': banner_pie
    }
    return render(request, 'detalle_articulo.html', context)


def buscar(request):
    texto = request.GET.get('search')
    try:
        zona_activa = get_zona_activa(request)
        negocios = Negocio.objects.filter(zona=zona_activa).filter(Q(nombre__icontains=texto) |
                                                                   Q(descripcion__icontains=texto) |
                                                                   Q(descripcion_corta__icontains=texto) |
                                                                   Q(sub_categoria__nombre__icontains=texto) |
                                                                   Q(servicios__nombre__icontains=texto)).distinct()
    except Exception:
        negocios = Negocio.objects.filter(Q(nombre__icontains=texto) |
                                          Q(descripcion__icontains=texto) |
                                          Q(descripcion_corta__icontains=texto) |
                                          Q(sub_categoria__nombre__icontains=texto) |
                                          Q(servicios__nombre__icontains=texto)).distinct()
    context = {
            'negocios': negocios,
            'cantidad_negocios': negocios.count(),
            'texto': texto
        }
    return render(request, 'resultado_busqueda.html', context)

qrofind_web/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    {% load thumbnail %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TuZONA.mx</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/utils.css' %}">
    <!--MATERIAL-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css"/>
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <!--End MATERIAl-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="{% static 'negocios/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/ver_tel_nopremium.js' %}"></script>
    <script src="{% static 'js/show_menu.js' %}"></script>
    <style>
        #menu-movil, #menu-desktop {
            display: none;
        }

        .mdl-navigation__link {
            font-weight: bold;
            text-transform: uppercase;
        }
    </style>
    {% block custom_statics %}

    {% endblock %}
</head>
<body style="background-color: rgba(192, 192, 192, 0.82)">
<div class="mdl-layout mdl-js-layout
            mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <a href="/" class="mdl-layout-title">
                <img src="{% static 'img/logo.png' %}" width="50px" class="img-responsive">
            </a>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                  mdl-textfield--floating-label mdl-textfield--align-right">
                <label class="mdl-button mdl-js-button mdl-button--icon"
                       for="fixed-header-drawer-exp">
                    <i class="material-icons">search</i>
                </label>
                <div class="mdl-textfield__expandable-holder">
                    <form action="#">
                        <input class="mdl-textfield__input" type="text" name="sample"
                               id="fixed-header-drawer-exp">
                    </form>
                </div>
            </div>
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                <a class="mdl-navigation__link" href="">Está buscando en {{ zona }}</a>
                <a class="mdl-navigation__link" href="{% url 'negocios:promociones' %}">Promociones</a>
                <a class="mdl-navigation__link" href="{% url 'negocios:anunciate' %}">Anúnciate</a>

            </nav>
        </div>
        <div class="mdl-layout__header-row mdl-layout--no-desktop-drawer-button mdl-layout--large-screen-only">
            <div class="mdl-layout-spacer"></div>
            <!-- Navigation -->
            <nav class="mdl-navigation">
                {% for categoria in categorias %}
                    <a class="mdl-navigation__link"
                       href="{% url 'negocios:negocios_categorias' slug_categoria=categoria.slug%}">
                        {{ categoria.nombre }}
                    </a>
                {% endfor %}
                <!-- Right aligned menu below button -->
                <button id="demo-menu-lower-right"
                        class="mdl-button mdl-js-button mdl-button--icon">
                    <i class="material-icons">more_vert</i>
                </button>

                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                    for="demo-menu-lower-right">
                    {% for restante in categorias_restantes %}
                        <li class="mdl-menu__item">
                            <a href="{% url 'negocios:negocios_categorias' slug_categoria=restante.slug %}">
                                {{ restante.nombre }}
                            </a>
                        </li>
                    {% endfor %}

                </ul>

            </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">QroFind</span>
        <nav class="mdl-navigation">
            {% for categoria in categorias %}
                <a class="mdl-navigation__link"
                   href="{% url 'negocios:negocios_categorias' slug_categoria=categoria.slug%}">
                    {{ categoria.nombre }}
                </a>
            {% endfor %}
            {% for categoria in categorias_restantes %}
                <a class="mdl-navigation__link"
                href="{% url 'negocios:negocios_categorias' slug_categoria=categoria.slug%}">{{ categoria.nombre }}</a>
            {% endfor %}
        </nav>
    </div>

    <main class="mdl-layout__content">
        <div class="page-content">
            {% block container %}

            {% endblock %}
        </div>
        <footer>
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col">
                    <p class="txt-center"> Todos los derechos reservados 2017</p>
                </div>
            </div>
        </footer>
    </main>
</div>


</body>
</html>

qrofind_web/main/templates/base_index.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>QroFind</title>
    <!-- Latest compiled and minified CSS -->
    <!--MATERIAL-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.red-blue.min.css"/>
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <!--End MATERIAl-->

    <link rel="stylesheet" href="{% static 'css/utils.css' %}">

    {% block custom_statics %}

    {% endblock %}
</head>
<body>
<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <a href="/" class="mdl-layout-title">
                <img src="{% static 'img/logo.png' %}" width="50px" class="img-responsive">
            </a>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>
            <!-- Navigation. We hide it in small screens. -->
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                {% for zona in zonas %}
                    <a class="mdl-navigation__link" href="{% url 'main:index' slug_zona=zona.slug %}">{{ zona }}</a>
                {% endfor %}
            </nav>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                  mdl-textfield--floating-label mdl-textfield--align-right">
                <label class="mdl-button mdl-js-button mdl-button--icon"
                       for="fixed-header-drawer-exp">
                    <i class="material-icons">search</i>
                </label>
                <div class="mdl-textfield__expandable-holder">
                    <form action="#">
                        <input class="mdl-textfield__input" type="text" name="sample"
                               id="fixed-header-drawer-exp">
                    </form>
                </div>
            </div>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">QroFind</span>
        <nav class="mdl-navigation">
             {% for zona in zonas %}
                    <a class="mdl-navigation__link" href="{% url 'main:index' slug_zona=zona.slug %}">{{ zona }}</a>
                {% endfor %}
        </nav>
    </div>
    <main class="mdl-layout__content">
        <div class="page-content"><!-- Your content goes here --></div>
    </main>
</div>

<div class="container">
    {% block content_home %}

    {% endblock %}
</div>
</body>
</html>

qrofind_web/main/templates/detalle_articulo.html
{% extends 'base_index.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load texto %}
{% block custom_statics %}
    <link rel="stylesheet" type="text/css" href="{% static 'negocios/vendors/slick/slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'negocios/vendors/slick/slick/slick-theme.css' %}"/>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'negocios/vendors/slick/slick/slick.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('#image-thumbs').slick({
                infinite: true,
                slidesToShow: 4,
            });
        });
    </script>
    <style>

        #image-thumbs {
            margin-top: 45px;
            margin-bottom: 25px;
        }
    </style>
{% endblock %}
{% block content_home %}
    <p><b>{{ articulo.titulo }}</b></p>
    <p>{{ articulo.zona }}</p>
    <p>{{ articulo.fecha }}</p>
    <img src="{{ articulo.imagen.url }}" class="img-responsive" alt="{{ articulo.titulo }}">
    <p class="mt10">
        {% autoescape off %}
            {% texto articulo.descripcion_larga %}
        {% endautoescape %}

    </p>
    <div id="image-thumbs">
        {% for imagen in articulo.imagenes.all %}
            <a class="mr10" href="{{ imagen.imagen.url }}" target="_blank">
                <img src="{{ imagen.imagen.url }}" height="250px"/>
            </a>
        {% endfor %}
    </div>
{% endblock %}

qrofind_web/main/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_statics %}
    <link rel="stylesheet" type="text/css" href="{% static 'negocios/vendors/slick/slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'negocios/vendors/slick/slick/slick-theme.css' %}"/>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'negocios/vendors/slick/slick/slick.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <script>
        $(document).ready(function () {
            $('.item-banner-nacional').slick({
                infinite: true,
                slidesToShow: 1,
                autoplay: true,
                autoplaySpeed: 2000
            });
            $(function () {
                $('#id_email').attr('placeholder', 'Correo electrónico');
            });
        });
    </script>
    <style>

    </style>
{% endblock %}
{% block container %}
    <h4>Negocios Destacados</h4>
    <div class="mdl-grid">
        {% for negocio in negocios_premium %}
                        {% include 'negocio/item_negocio.html' with negocio=negocio %}

        {% endfor %}

    </div>
    <h4>{{ primera_subcategorias_inicio }}</h4>
    <div class="mdl-grid">
        {% for negocio in negocios_primera_subcategoria %}
            {% include 'negocio/item_negocio.html' with negocio=negocio %}
        {% endfor %}

    </div>
    <h4>{{ segunda_subcategorias_inicio }}</h4>
    <div class="mdl-grid">
        {% for negocio in negocios_segunda_subcategoria %}
            {% include 'negocio/item_negocio.html' with negocio=negocio %}
        {% endfor %}

    </div>
{% endblock %}

qrofind_web/main/templates/inicio_zonas.html
{% extends 'base_index.html' %}
{% load staticfiles %}
{% block content_home %}
{% endblock %}

qrofind_web/main/templates/item_articulo.html
{% load thumbnail %}

<div class="col-sm-6 col-md-3">
    <div class="thumbnail">
        <img src="{{ articulo.imagen|thumbnail_url:'thumb_negocio' }}" alt="{{ articulo.titulo }}">
        <div class="caption">
            <h4 class="titulo-negocio-thumbs">{{ articulo }}</h4>
            <p class="">{{ articulo.zona }}</p>
            <p class="desc-negocio-thumbs">{{ articulo.descripcion_corta }}</p>
            <a href="{% url 'main:detalle_articulo' slug_articulo=articulo.slug %}">Leer m&aacute;s</a>
        </div>
    </div>
</div>

qrofind_web/main/templates/promociones_generales.html
{% extends 'base_index.html' %}
{% load staticfiles %}
{% block custom_statics %}
    <link rel="stylesheet" href="{% static 'negocios/css/categorias.css' %}">
    <script>
        $(function () {
            $('.titulo-promocion:even').css("background-color", "#ED1C24");
            $('.titulo-promocion:odd').css("background-color", "#3871C1");
        })
    </script>
{% endblock %}
{% block content_home %}
    <section id="contenedor-promociones" class="row">

        {% if promociones|length > 0 %}
            <h2>PROMOCIONES ACTIVAS</h2>
            <div class="row">
                {% for promocion in promociones %}
                    {% include 'negocio/item_promocion.html' with promocion=promocion %}
                {% endfor %}
            </div>
        {% else %}
            <h2>NO HAY NEGOCIOS PROMOCIONADOS</h2>

        {% endif %}
    </section>
{% endblock %}

qrofind_web/main/templates/resultado_busqueda.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_statics %}
{% endblock %}
{% block container %}
    <section id="contenedor-resultados" class="row">
        <p>Se encontraron <strong>{{ cantidad_negocios }} </strong> coincidencias con <strong>{{ texto }}</strong>
        </p>

        {% if negocios|length > 0 %}
            {% for negocio in negocios %}
                {% include 'negocio/item_negocio.html' with negocio=negocio chico=0 %}
            {% endfor %}
        {% else %}
            <h3 class="col-md-12">NO hay resultados que mostrar</h3>
        {% endif %}
    </section>
{% endblock %}

qrofind_web/main/templates/texto.html
{{ texto }}