qrofind_web/negocios/urls.py
from django.conf.urls import include, url
from qrofind_web.negocios import views
urlpatterns = [
    url(r'^categoria/(?P<slug_categoria>.+)/$', views.negocios_categorias, name='negocios_categorias'),
    url(r'^detalle/negocio/(?P<slug_negocio>.+)/$', views.detalle_negocio, name='detalle_negocio'),
    url(r'^registro/clic/$', views.registro_clic_negocio, name='registro_clic_negocio'),
    url(r'^promociones/$', views.promociones, name='promociones'),
    url(r'^anunciate/$', views.anunciate, name='anunciate'),
    url(r'^inicio/anunciate/$', views.anunciate_inicio, name='anunciate_inicio'),
]

qrofind_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Administrador Zona Real'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('qrofind_web.main.urls', namespace="main")),
    url(r'^', include('qrofind_web.negocios.urls', namespace="negocios")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qrofind_web/negocios/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Transpose
from qrofind_web.utils import PathAndRename
from django.template.defaultfilters import slugify
from geoposition.fields import GeopositionField

path_and_rename_categorias = PathAndRename("categorias")
path_and_rename_servicios = PathAndRename("servicios")
path_and_rename_promociones = PathAndRename("promociones")
path_and_rename_negocios = PathAndRename("negocios")


class Categoria(models.Model):
    zona = models.ForeignKey('main.Zona', null=True, blank=True, related_name='categorias')
    nombre = models.CharField(max_length=30)
    slug = models.SlugField(max_length=60, editable=False)
    orden = models.IntegerField(default=0)
    banner = ProcessedImageField(max_length=255, blank=True, null=True,
                                 upload_to=path_and_rename_categorias,
                                 processors=[Transpose()])
    # inicio = models.BooleanField(default=False, help_text='Marque si quiere esta categoría en la página de inicio')

    def __str__(self):
        return "{}-{}".format(self.nombre,self.zona)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        return super(Categoria, self).save(*args, **kwargs)


class Subcategoria(models.Model):
    categoria = models.ForeignKey('negocios.Categoria', related_name='subcategorias')
    nombre = models.CharField(max_length=30)
    slug = models.SlugField(max_length=60, editable=False)
    orden = models.IntegerField(default=0)
    inicio = models.BooleanField(default=False, help_text='Marque si quiere esta subcategoría en la página de inicio')

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        return super(Subcategoria, self).save(*args, **kwargs)

    def get_negocios_ordenados(self):
        return self.negocios.all().order_by('orden_subcategoria')

    def get_zona(self):
        return self.categoria.zona


class Servicio(models.Model):
    nombre = models.CharField(max_length=30)
    imagen = ProcessedImageField(max_length=255, blank=True, null=True,
                                 upload_to=path_and_rename_servicios,
                                 processors=[Transpose()])

    def __str__(self):
        return self.nombre


class Promocion(models.Model):
    negocio = models.ForeignKey('negocios.Negocio', related_name='promociones')
    titulo = models.CharField(max_length=25, blank=True)
    texto = models.TextField()
    imagen = ProcessedImageField(max_length=255, blank=True, null=True,
                                 upload_to=path_and_rename_promociones,
                                 processors=[Transpose()])
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()

    def __str__(self):
        return self.texto


class Negocio(models.Model):
    sub_categoria = models.ManyToManyField('negocios.Subcategoria', related_name='negocios')
    zona = models.ForeignKey('main.Zona', related_name='negocios')
    imagen_principal = ProcessedImageField(max_length=255, null=True,
                                           upload_to=path_and_rename_negocios,
                                           processors=[Transpose()])
    imagen_promocion = ProcessedImageField(max_length=255, null=True, blank=True,
                                           upload_to=path_and_rename_negocios,
                                           processors=[Transpose()])
    nombre = models.CharField(max_length=30)
    telefono1 = models.CharField(max_length=30, blank=True, null=True)
    telefono2 = models.CharField(max_length=30, blank=True, null=True)
    telefono3 = models.CharField(max_length=30, blank=True, null=True)
    telefono4 = models.CharField(max_length=30, blank=True, null=True)
    direccion = models.TextField(blank=True, null=True)
    horario = models.TextField(blank=True, null=True)
    pagina_web = models.URLField(max_length=200, blank=True, null=True)
    descripcion_corta = models.CharField(max_length=60,blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    position = GeopositionField(db_index=True, blank=True, null=True)
    # latitude = models.FloatField(db_index=True, blank=True, null=True)
    # longitude = models.FloatField(db_index=True, blank=True, null=True)
    email_contacto = models.CharField(max_length=50, blank=True, null=True)
    email_contacto2 = models.CharField(max_length=50, blank=True, null=True)
    email_contacto3 = models.CharField(max_length=50, blank=True, null=True)
    servicios = models.ManyToManyField('negocios.Servicio', blank=True)
    facebook_url = models.URLField(max_length=200, blank=True, null=True)
    twitter_url = models.URLField(max_length=200, blank=True, null=True)
    instagram_url = models.URLField(max_length=200, blank=True, null=True)
    yotutbe_url = models.URLField(max_length=200, blank=True, null=True)
    google_plus_url = models.URLField(max_length=200, blank=True, null=True)
    es_premium = models.BooleanField(default=False)
    promocionado = models.BooleanField(default=False)
    servicio_domicilio = models.BooleanField(default=False)
    orden = models.IntegerField(default=0, help_text='Orden para la promoción')
    orden_subcategoria = models.IntegerField(default=0, help_text='Orden para la subcategoria')
    cantidad_clic = models.IntegerField(editable=False, default=0, help_text='Solo para negocios no premium clics en ver teléfono')
    slug = models.SlugField(max_length=60, editable=False, null=True)

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        return super(Negocio, self).save(*args, **kwargs)


class FotoNegocio(models.Model):
    texto = models.CharField(max_length=100, blank=True, null=True)
    imagen = ProcessedImageField(max_length=255, null=True,
                                 upload_to=path_and_rename_negocios,
                                 processors=[Transpose()])
    negocio = models.ForeignKey('negocios.Negocio', related_name="imagenes")
    orden = models.IntegerField(default=0)

    def __str__(self):
        return self.texto


class FotoNegocioAmplia(models.Model):
    texto = models.CharField(max_length=100, blank=True, null=True)
    imagen = ProcessedImageField(max_length=255, null=True,
                                 upload_to=path_and_rename_negocios,
                                 processors=[Transpose()])
    negocio = models.ForeignKey('negocios.Negocio', related_name="imagenes_amplias")
    orden = models.IntegerField(default=0)

    def __str__(self):
        return self.texto


class RegistroContato(models.Model):
    negocio = models.ForeignKey('negocios.Negocio')
    texto = models.CharField(max_length=500, blank=True, null=True)
    correo = models.CharField(max_length=50, blank=True, null=True)
    mensaje_de = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return "contacto a {}".format(self.negocio)

qrofind_web/negocios/forms.py
from django import forms
from qrofind_web.negocios.models import *

class ContactoForm(forms.Form):

    nombre = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    email = forms.EmailField()
    mensaje = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'placeholder': 'Mensaje'}))


class AnunciateForm(forms.Form):

    nombre = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    email = forms.EmailField()
    nombre_negocio = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Nombre del negocio'}))
    telefono = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Teléfono'}))
    direccion = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'placeholder': 'Dirección'}))
    mensaje = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'placeholder': 'Mensaje'}))



class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['zona', 'nombre', 'orden', 'banner']

qrofind_web/negocios/views.py
from django.shortcuts import render
from qrofind_web.negocios.forms import *
from django.core.mail import send_mail
from django.conf import settings
import datetime
from django.http import HttpResponse
from qrofind_web.negocios.utils import *
import json


# Create your views here.


def negocios_categorias(request, slug_categoria):
    zona = Zona.objects.get(slug=request.session['slug_zona_activa'])
    categoria = Categoria.objects.get(slug=slug_categoria, zona=zona)
    negocios_promocionados = None
    subcategorias = None
    if slug_categoria == "servicio-a-domicilio":
        negocios_promocionados = Negocio.objects.filter(promocionado=True,
                                                        zona=zona, servicio_domicilio=True).order_by('orden').distinct()
        subcategorias = Subcategoria.objects.filter(negocios__servicio_domicilio=True,categoria__zona=zona).order_by('orden').distinct()

    if slug_categoria != "servicio-a-domicilio":
        negocios_promocionados = Negocio.objects.filter(sub_categoria__categoria=categoria, promocionado=True,
                                                        zona=zona).order_by('orden').distinct()
        subcategorias = categoria.subcategorias.all().order_by('orden').distinct()
    context = {
        'categoria': categoria,
        'subcategorias': subcategorias,
        'negocios_promocionados': negocios_promocionados,
    }
    return render(request, 'negocio/categoria.html', context)


def detalle_negocio(request, slug_negocio):
    contacto_form = ContactoForm()
    promociones = None
    zona = Zona.objects.get(slug=request.session['slug_zona_activa'])
    negocio = Negocio.objects.get(slug=slug_negocio, zona=zona)
    promociones_generales = Promocion.objects.filter(negocio=negocio, fecha_inicio__lte=datetime.datetime.now(),
                                                     fecha_fin__gte=datetime.datetime.now()).order_by('?')[:1]
    mensaje_contacto = None
    # Registro de clic

    if promociones_generales.count() > 0:
        promociones = promociones_generales[0]
    if request.method == 'POST':
        contacto_form = ContactoForm(request.POST)
        if contacto_form.is_valid():
            nombre = contacto_form.cleaned_data['nombre']
            email = contacto_form.cleaned_data['email']
            negocio_contacto = negocio.email_contacto
            listado_correos = ["roberto.nunez@dgtalgroup.com", "jorge@dgtalgroup.com", negocio_contacto]

            if negocio.email_contacto2 != "":
                listado_correos.append(negocio.email_contacto2)

            if negocio.email_contacto3 != "":
                listado_correos.append(negocio.email_contacto3)

            mensaje = contacto_form.cleaned_data['mensaje']
            texto = 'De {} email: {} \n Mensjaje: {}'.format(nombre, email, mensaje)

            send_mail('Correo desde la web', texto, settings.DEFAULT_FROM_EMAIL,
                      listado_correos, fail_silently=True)

            mensaje_contacto = "Se ha enviado su mensaje"

            registro_contacto = RegistroContato()
            registro_contacto.negocio = negocio
            registro_contacto.correo = email
            registro_contacto.mensaje_de = nombre
            registro_contacto.texto = mensaje
            registro_contacto.save()
    context = {
        'negocio': negocio,
        'promociones_generales': promociones,
        'mensaje_contacto': mensaje_contacto,
        'contacto_form': contacto_form
    }
    return render(request, 'negocio/detalle_negocio.html', context)


def promociones(request):
    zona_activa = get_zona_activa(request)
    listado_promociones = Promocion.objects.filter(negocio__zona=zona_activa,
                                                   fecha_inicio__lte=datetime.datetime.now(),
                                                   fecha_fin__gte=datetime.datetime.now())
    banner = Banner.objects.filter(seccion=0).order_by('-orden')[:1]
    context = {'banner': banner, 'promociones': listado_promociones}
    return render(request, 'negocio/promociones.html', context)


def registro_clic_negocio(request):
    negocio_id = request.GET.get('negocio')
    negocio = Negocio.objects.get(pk=negocio_id)
    cantidad_clic = negocio.cantidad_clic
    nueva_cantidad = cantidad_clic + 1
    negocio.cantidad_clic = nueva_cantidad
    negocio.save()
    json_data = {'rc': 0}
    return HttpResponse(json.dumps(json_data), content_type='application/json')


def anunciate(request):
    context = get_anunciate_form(request)
    return render(request, 'negocio/anunciate.html', context)


def anunciate_inicio(request):
    zonas = Zona.objects.all().exclude(slug='default')[:7]

    context = get_anunciate_form(request)
    context['zonas'] = zonas
    return render(request, 'negocio/anunciate_home.html', context)


def get_anunciate_form(request):
    form = AnunciateForm()
    mensaje = None
    if request.method == 'POST':
        form = AnunciateForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            nombre_negocio = form.cleaned_data['nombre_negocio']
            email = form.cleaned_data['email']
            direccion = form.cleaned_data['direccion']
            telefono = form.cleaned_data['telefono']
            mensaje = form.cleaned_data['mensaje']
            texto = 'De {} email: {} \n nombre negocio {} \n Direccion {}' \
                    ' \n Teléfono {} \n Mensaje: {}'.format(nombre,
                                                            email,
                                                            nombre_negocio,
                                                            direccion,
                                                            telefono,
                                                            mensaje)
            send_mail('Correo desde la web para anunciante', texto, settings.DEFAULT_FROM_EMAIL,
                      ['pedro@tuzona.mx'], fail_silently=True)
            mensaje = "Se ha enviado su mensaje"

    return {'form': form, 'mensaje': mensaje}

qrofind_web/negocios/templates/negocio/anunciate.html
{% extends 'base.html' %}
{% block container %}
{#    <div class="row text-center">#}
{#        <h4>#}
{#            El 98% de la gente de Zona Real tiene un Smartphone y acceso a internet</h4>#}
{#        <h4>Un directorio que SI puedes llevar contigo a todos lados</h4>#}
{#        <h4>Hay que cuidar el planeta y nuestros árboles</h4>#}
{##}
{#    </div>#}
   <div class="row bg-azul-claro txt-blanco pd15">
        <h3>¿Quieres exisitir en T&uacute; Zona?</h3>
        <div class="col-sm-12 col-md-6">
            <h4>
                Suscríbete al Directorio PREMIUM
                de T&uacute; Zona
            </h4>
            <ul>
                <li>
                    Prescencia en Directorio T&uacute; Zona con:
                </li>
                <li>
                    - Nombre y Logo
                </li>
                <li>
                    - Teléfono
                </li>
                <li>
                    - Dirección
                </li>
                <li>
                    - Horarios
                </li>
                <li>
                    - Ubicación en el mapa
                </li>
                <li>
                    - Fotos
                </li>
                <li>
                    - Promociones
                </li>
                <li>
                    - Menú / Productos / Servicios
                </li>
                <li>
                    - Servicios Adicionales
                </li>
                <li>
                    - Actualiza tu perfil
                </li>
                <li>
                    - Enlaces a tus Redes sociales
                </li>
                <li>
                    - Enlaces a tu Pag. Web
                </li>
            </ul>
        </div>
        <div class="col-sm-12 col-md-6">
            {% if mensaje != None %}
                <h3>{{ mensaje }}</h3>
            {% endif %}
            <form id="anunciate-form" action="{% url 'negocios:anunciate' %}" method="POST"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <div class="form-group">
                            {{ form.nombre }}
                            {{ form.nombre.error_messages }}
                        </div>
                        <div class="form-group">
                            {{ form.email }}
                            {{ form.email.error_messages }}
                        </div>
                        <div class="form-group">
                            {{ form.nombre_negocio }}
                            {{ form.nombre_negocio.error_messages }}
                        </div>

                        <div class="form-group">
                            {{ form.telefono }}
                            {{ form.telefono.error_messages }}
                        </div>
                        <div class="form-group">
                            {{ form.direccion }}
                            {{ form.direccion.error_messages }}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-8">
                        <div class="form-group">
                            {{ form.mensaje }}
                            {{ form.mensaje.error_messages }}
                        </div>
                        <button class="btn btn-default">Enviar</button>

                    </div>
                </div>


            </form>
        </div>
    </div>
{% endblock %}

qrofind_web/negocios/templates/negocio/anunciate_home.html
{% extends 'base_index.html' %}
{% block anunciate %}
{#    <div class="row text-center">#}
{#        <h4>#}
{#            El 98% de la gente de Zona Real tiene un Smartphone y acceso a internet</h4>#}
{#        <h4>Un directorio que SI puedes llevar contigo a todos lados</h4>#}
{#        <h4>Hay que cuidar el planeta y nuestros árboles</h4>#}
{##}
{#    </div>#}
    <div class="row bg-azul-claro txt-blanco pd15">
        <h3>¿Quieres exisitir en T&uacute; Zona?</h3>
        <div class="col-sm-12 col-md-6">
            <h4>
                Suscríbete al Directorio PREMIUM
                de T&uacute; Zona
            </h4>
            <ul>
                <li>
                    Prescencia en Directorio T&uacute; Zona con:
                </li>
                <li>
                    - Nombre y Logo
                </li>
                <li>
                    - Teléfono
                </li>
                <li>
                    - Dirección
                </li>
                <li>
                    - Horarios
                </li>
                <li>
                    - Ubicación en el mapa
                </li>
                <li>
                    - Fotos
                </li>
                <li>
                    - Promociones
                </li>
                <li>
                    - Menú / Productos / Servicios
                </li>
                <li>
                    - Servicios Adicionales
                </li>
                <li>
                    - Actualiza tu perfil
                </li>
                <li>
                    - Enlaces a tus Redes sociales
                </li>
                <li>
                    - Enlaces a tu Pag. Web
                </li>
            </ul>
        </div>
        <div class="col-sm-12 col-md-6">
            {% if mensaje != None %}
                <h3>{{ mensaje }}</h3>
            {% endif %}
            <form id="anunciate-form" action="{% url 'negocios:anunciate' %}" method="POST"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <div class="form-group">
                            {{ form.nombre }}
                            {{ form.nombre.error_messages }}
                        </div>
                        <div class="form-group">
                            {{ form.email }}
                            {{ form.email.error_messages }}
                        </div>
                        <div class="form-group">
                            {{ form.nombre_negocio }}
                            {{ form.nombre_negocio.error_messages }}
                        </div>

                        <div class="form-group">
                            {{ form.telefono }}
                            {{ form.telefono.error_messages }}
                        </div>
                        <div class="form-group">
                            {{ form.direccion }}
                            {{ form.direccion.error_messages }}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-8">
                        <div class="form-group">
                            {{ form.mensaje }}
                            {{ form.mensaje.error_messages }}
                        </div>
                        <button class="btn btn-default">Enviar</button>

                    </div>
                </div>


            </form>
        </div>
    </div>
{% endblock %}

qrofind_web/negocios/templates/negocio/categoria.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_statics %}
    <link rel="stylesheet" href="{% static 'negocios/css/categorias.css' %}">
    <script>
        jQuery(document).ready(function () {
            var offset = 220;
            var duration = 500;
            jQuery(window).scroll(function () {
                if (jQuery(this).scrollTop() > offset) {
                    jQuery('.back-to-top').fadeIn(duration);
                } else {
                    jQuery('.back-to-top').fadeOut(duration);
                }
            });

            jQuery('.back-to-top').click(function (event) {
                event.preventDefault();
                jQuery('html, body').animate({scrollTop: 0}, duration);
                return false;
            })
        });
    </script>
{% endblock %}
{% block container %}
    <section id="contenedor-categorias">
        <div id="contenedor-subcategorias">
            {% for subcategoria in subcategorias %}
                <span class="mdl-chip">
                    <span class="mdl-chip__text">
                        <a href="#{{ subcategoria.slug }}">{{ subcategoria }}</a>
                    </span>
                </span>
            {% endfor %}
            <div class="clearfix"></div>
        </div>
        {% if negocios_promocionados|length > 0 %}
            <h4>NEGOCIOS PROMOCIONADOS</h4>
            <div class="mdl-grid">
                {% for negocios_promocionado in negocios_promocionados %}
                    {% include 'negocio/item_negocio.html' with negocio=negocios_promocionado %}
                {% endfor %}
            </div>

        {% endif %}

        {% if categoria.slug == "servicio-a-domicilio" %}
            {% for subcategoria in subcategorias %}
                <h3 id="{{ subcategoria.slug }}">{{ subcategoria }}</h3>
            <div class="mdl-grid">
                    {% if subcategoria.negocios.all|length > 0 %}
                        {% for negocio in subcategoria.get_negocios_ordenados %}
                            {% if negocio.servicio_domicilio %}
                                {% include 'negocio/item_negocio.html' with negocio=negocio%}
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <h3 class="col-md-12">NO hay productos en esta categoría</h3>
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}

        {% if categoria.slug != "servicio-a-domicilio" %}
            {% for subcategoria in subcategorias %}
                <h3 id="{{ subcategoria.slug }}">{{ subcategoria }}</h3>
            <div class="mdl-grid">
                    {% if subcategoria.negocios.all|length > 0 %}
                        {% for negocio in subcategoria.get_negocios_ordenados %}
                            {% include 'negocio/item_negocio.html' with negocio=negocio%}
                        {% endfor %}
                    {% else %}
                        <h3 class="col-md-12">NO hay productos en esta categoría</h3>
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}

        <a href="#" class="back-to-top">Ir hasta arriba</a>
    </section>
{% endblock %}

qrofind_web/negocios/templates/negocio/item_negocio.html
{% load thumbnail %}
<div class="mdl-cell mdl-cell--3-col  mdl-cell--12-col-phone">
    <div class="mdl-card mdl-shadow--2dp">
        <div class="mdl-card__media" style="background-image:
                url('/media/{{ negocio.imagen_principal }}');background-size: cover">

        </div>
        <div class="mdl-card__title">
            <h1 class="mdl-card__title-text">{{ negocio.nombre }}</h1>
        </div>
        <div class="mdl-card__supporting-text">
            <p>{{ negocio.descripcion_corta }}</p>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            {% if negocio.es_premium %}
                <a href="{% url 'negocios:detalle_negocio' slug_negocio=negocio.slug %}"
                   class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                    Perfil negocio
                </a>

                <div class="mdl-layout-spacer"></div>
                <a href="tel:{{ negocio.telefono1 }}" class="mdl-button mdl-button--icon mdl-button--colored">
                    <i class="material-icons">phone</i>
                </a>
                <a
                        class="mdl-button mdl-button--icon mdl-button--colored"
                        target="_blank"
                        href="https://www.google.com/maps?q={{ negocio.position.latitude }},{{ negocio.position.longitude }}">
                    <i class="material-icons">place</i>
                </a>
            {% else %}
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                  <i class="material-icons">phone</i>
                    {{ negocio.telefono1 }}
                </a>
            {% endif %}
        </div>

    </div>
</div>

qrofind_web/negocios/templates/negocio/item_promocion.html
{% load thumbnail %}

<div class="col-sm-6 col-md-3">
    <div class="thumbnail">
        <a href="{% url 'negocios:detalle_negocio' slug_negocio=promocion.negocio.slug %}" title="{{ promocion.negocio.slug }}">
            <div class="titulo-promocion">{{ promocion.titulo }}</div>
            <img src="{{ promocion.imagen|thumbnail_url:'thumb_negocio' }}" alt="{{ promocion }}">
            <div class="caption">
                <h4><b>{{ promocion.negocio }}</b></h4>
                {% for subcategoria in promocion.negocio.sub_categoria.all|slice:":1" %}
                    <p class="categoria-negocio-promocion">{{ subcategoria }}</p>
                {% endfor %}
                <p>{{ promocion.texto }}</p>
                <p>Tel: {{ promocion.negocio.telefono }}</p>
            </div>
        </a>
    </div>
</div>

qrofind_web/negocios/templates/negocio/promociones.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_statics %}
    <link rel="stylesheet" href="{% static 'negocios/css/categorias.css' %}">
    <script>
        $(function () {
            $('.titulo-promocion:even').css("background-color", "#ED1C24");
            $('.titulo-promocion:odd').css("background-color", "#3871C1");
        })
    </script>
{% endblock %}
{% block container %}
    <section id="contenedor-promociones" class="row">
        <section id="banner-subcategoria">
            {% if banner|length > 0 %}
                {% for imagen in banner %}
                    {% if imagen.link != "" and imagen.pagina_externa == True %}
                        <a href="{{ imagen.link }}" target="_blank">
                    {% endif %}
                    {% if imagen.link != "" and imagen.pagina_externa == False %}
                        <a href="{{ imagen.link }}" target="_blank">
                    {% endif %}
                <img src="{{ imagen.imagen.url }}" class="" width="100%" height="300px" title="Banner">
                    {% if imagen.link != "" %}
                        </a>
                    {% endif %}
                {% endfor %}

            {% endif %}
        </section>

        {% if promociones|length > 0 %}
            <h2>PROMOCIONES ACTIVAS</h2>
            <div class="row">
                {% for promocion in promociones %}
                    {% include 'negocio/item_promocion.html' with promocion=promocion %}
                {% endfor %}
            </div>
        {% else %}
            <h2>NO HAY NEGOCIOS PROMOCIONADOS</h2>

        {% endif %}

        {% for subcategoria in subcategorias %}
            <h3 id="{{ subcategoria.slug }}">{{ subcategoria }}</h3>
            <div class="row">
                {% if subcategoria.negocios.all|length > 0 %}
                    {% for negocio in subcategoria.negocios.all %}
                        {% include 'negocio/item_negocio.html' with negocio=negocio chico=0 %}
                    {% endfor %}
                {% else %}
                    <h3 class="col-md-12">NO hay productos en esta categoría</h3>
                {% endif %}
            </div>
        {% endfor %}

    </section>
{% endblock %}